/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package up.cmsc141.julia.mp4.test2;

import java.util.ArrayList;
import java.util.List;
import java.util.Stack;

/**
 *
 * @author juliam
 */
public class Checker {
    
    List<Token> tokens = new ArrayList<Token>();
    ArrayList<State> finalStates = new ArrayList<State>() {{
        add(State.SEMICOLONSTATE);
        add(State.SEMICOLONINC);
        add(State.CLOSEBRACE);
        add(State.SEMICOLONFINAL);
    }};
    
//    private State[][] table = {
//        //                                              CATEGORIES
//        //  *STATE*     OPENPARENS        CLOSEPARENS        OPENBRACKET        CLOSEBRACKET       COMMA             
//        /*  START */{   State.TYPEDEC,    State.TYPEDEC,     State.VARTEXTDEC,  State.INVALID,     State.INVALID },
//      /*  TYPEDEC */{   State.VARTEXTDEC, State.INVALID,     State.INVALID,     State.COMMASTATE,  State.INVALID },
//   /*  VARTEXTDEC */{   State.COMMASTATE, State.TYPEDEC,     State.INVALID,     State.TYPEDEC,     State.INVALID },
//   /*  COMMASTATE */{   State.TYPEDEC,    State.INVALID,     State.TYPEDEC,     State.TYPEDEC,     State.INVALID },
//    };
    
    //{   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,    State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,  State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    private State[][] table = {
        //                                              CATEGORIES
        //  *STATE*     OPENPARENS                  CLOSEPARENS                 OPENBRACKET                 CLOSEBRACKET            COMMA               SEMICOLON               ASTERISK                SIGNED              UNSIGNED                CHAR                SHORT               INT                 LONG                FLOAT               DOUBLE              VOID                NUMTEXT             VARTEXT             FUNCTEXT                INVALIDCATEG                ANDOR               COMPARARTOR             OPERATION               EQUALS              INCDEC              FOR                 CLOSEBRACE              OPENBRACE                          
        /*  START */    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.REGQUALI,     State.REGQUALI,         State.TYPEDEC,      State.SHORTTYPE,    State.TYPEDEC,      State.LONGFIRST,    State.TYPEDEC,      State.TYPEDEC,      State.TYPEDEC,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*  TYPEDEC */    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASTERISKSTATE,    State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTDEC,   State.FUNCTEXTDEC,      State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*  VARTEXTDEC */    {   State.INVALID,          State.INVALID,              State.OPENBRACKETSTATE,     State.INVALID,          State.COMMASTATE,   State.SEMICOLONSTATE,   State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*  COMMASTATE */    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASTERISKSTATE,    State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTDEC,   State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*ASTERISKSTATE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASTERISKSTATE,    State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTDEC,   State.FUNCTEXTDEC,      State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
        /*REGQUALI*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.TYPEDEC,      State.SHORTTYPE,    State.TYPEDEC,      State.LONGFIRST,    State.TYPEDEC,      State.TYPEDEC,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*LONGFIRST*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASTERISKSTATE,    State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEDEC,      State.LONGSECOND,   State.INVALID,      State.TYPEDEC,      State.INVALID,      State.INVALID,      State.VARTEXTDEC,   State.FUNCTEXTDEC,      State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*LONGSECOND*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASTERISKSTATE,    State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEDEC,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTDEC,   State.FUNCTEXTDEC,      State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*SHORTTYPE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASTERISKSTATE,    State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEDEC,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTDEC,   State.FUNCTEXTDEC,      State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
        /*VOIDTYPE*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
  /*SEMICOLONSTATE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
/*OPENBRACKETSTATE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.CLOSEBRACKETSTATE,State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMTEXTSTATE, State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    /*NUMTEXTSTATE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.CLOSEBRACKETSTATE,State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
/*CLOSEBRACKETSTATE*/   {   State.INVALID,          State.INVALID,              State.OPENBRACKETSTATE,     State.INVALID,          State.INVALID,      State.SEMICOLONSTATE,   State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
     /*FUNCTEXTDEC*/    {   State.OPENPARENSSTATE,  State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
 /*OPENPARENSSTATE*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.REGQUALIFUNC, State.REGQUALIFUNC,     State.TYPEFUNC,     State.SHORTTYPEFUNC,State.TYPEFUNC,     State.LONGFIRSTFUNC,State.TYPEFUNC,     State.TYPEFUNC,     State.VOIDTYPE,     State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
        /*TYPEFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.OPENBRACKETFUNC,      State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.ASTERISKFUNC,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTFUNC,  State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},   
     /*VARTEXTFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.OPENBRACKETFUNC,      State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*COMMAFUNC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.TYPEFUNC,     State.SHORTTYPEFUNC,State.TYPEFUNC,     State.LONGFIRSTFUNC,State.TYPEFUNC,     State.TYPEFUNC,     State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
 /*OPENBRACKETFUNC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.CLOSEBRACKETFUNC, State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMTEXTFUNC,  State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
     /*NUMTEXTFUNC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.CLOSEBRACKETFUNC, State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
/*CLOSEBRACKETFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.OPENBRACKETFUNC,      State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    /*ASTERISKFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.INVALID,              State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.ASTERISKFUNC,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTFUNC,  State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
/*CLOSEPARENSSTATE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONSTATE,   State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    /*REGQUALIFUNC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.TYPEFUNC,     State.SHORTTYPEFUNC,State.TYPEFUNC,     State.LONGFIRSTFUNC,State.TYPEFUNC,     State.TYPEFUNC,     State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*LONGFIRSTFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.OPENBRACKETFUNC,      State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.ASTERISKFUNC,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.LONGSECONDFUNC,State.INVALID,     State.TYPEFUNC,     State.INVALID,      State.INVALID,      State.VARTEXTFUNC,  State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
  /*LONGSECONDFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.OPENBRACKETFUNC,      State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.ASTERISKFUNC,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEFUNC,     State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTFUNC,  State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*SHORTTYPEFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.OPENBRACKETFUNC,      State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.ASTERISKFUNC,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEFUNC,     State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTFUNC,  State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    /*INVALIDSTATE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},

        //  *STATE*     OPENPARENS                  CLOSEPARENS                 OPENBRACKET                 CLOSEBRACKET            COMMA               SEMICOLON               ASTERISK                SIGNED              UNSIGNED                CHAR                SHORT               INT                 LONG                FLOAT               DOUBLE              VOID                NUMTEXT             VARTEXT             FUNCTEXT                INVALIDCATEG                ANDOR               COMPARARTOR             OPERATION               EQUALS              INCDEC              FOR                       
    //28
        /*STARTFOR*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.FORSTATE,      State.INVALID,      State.INVALID},
        /*FORSTATE*/    {   State.OPENPARENSFOR,    State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,       State.INVALID,      State.INVALID},
   /*OPENPARENSFOR*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONINIT,    State.INVALID,          State.REGQUALIINIT, State.REGQUALIINIT,     State.TYPEDEC,      State.SHORTINIT,    State.TYPEDEC,      State.LONGFIRSTINIT,State.TYPEDEC,     State.TYPEDEC,      State.TYPEDEC,      State.INVALID,      State.IDINIT,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,       State.INVALID,      State.INVALID},
    /*REGQUALIINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.TYPEDECINIT,  State.SHORTINIT,    State.TYPEDECINIT,  State.LONGFIRSTINIT,State.TYPEDECINIT, State.TYPEDECINIT,  State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,       State.INVALID,      State.INVALID},
   /*LONGFIRSTINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.LONGSECONDFOR,State.INVALID,      State.TYPEDECINIT,  State.INVALID,      State.INVALID,      State.IDINIT,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*LONGSECONDFOR*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEDECINIT,  State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDINIT,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*SHORTINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEDECINIT,  State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDINIT,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
          /*IDINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.COMMAINIT,    State.SEMICOLONINIT,    State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.ASSIGNINIT,   State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*SEMICOLONINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONCOND,    State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDCOND,       State.IDCOND,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
     /*TYPEDECINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDINIT,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*COMMAINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDINIT,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,           State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*ASSIGNINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINIT,      State.IDINITTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
         /*NUMINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.COMMAINIT,    State.SEMICOLONINIT,    State.OPINIT,           State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.OPINIT,           State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*IDINITTWO*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.COMMAINIT,    State.SEMICOLONINIT,    State.OPINIT,           State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.OPINIT,           State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
          /*OPINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINIT,      State.IDINIT,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
          /*IDCOND*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONCOND,    State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.COMPARATOR,       State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*COMPARATOR*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMCOND,      State.IDCONDTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*IDCONDTWO*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONCOND,    State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
         /*NUMCOND*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONCOND,    State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.ANDOR,        State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
           /*ANDOR*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDCOND,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*SEMICOLONCOND*/    {   State.INVALID,          State.CLOSEPARENSFOR,       State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDINC,        State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
           /*IDINC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.ASSIGNINC,    State.INCDEC,       State.INVALID,      State.INVALID,      State.INVALID},
    //50          
          /*INCDEC*/    {   State.INVALID,          State.CLOSEPARENSFOR,       State.INVALID,              State.INVALID,          State.COMMAINC,     State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*ASSIGNINC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINC,       State.IDINCTWO,     State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
        /*COMMAINC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDINC,        State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
  /*CLOSEPARENSFOR*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONINC,     State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.OPENBRACE},
        /*IDINCTWO*/    {   State.INVALID,          State.CLOSEPARENSFOR,       State.INVALID,              State.INVALID,          State.COMMAINC,     State.INVALID,          State.OPINC,            State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.OPINC,            State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
          /*NUMINC*/    {   State.INVALID,          State.CLOSEPARENSFOR,       State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.OPINC,            State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.OPINC,            State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
           /*OPINC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINC,       State.IDINCTWO,     State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    /*SEMICOLONINC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*OPENBRACE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.REGQUALIFORB, State.REGQUALIFORB,     State.TYPEDECFORB,  State.SHORTFORB,    State.TYPEDECFORB,  State.LONGFIRSTFORB,State.TYPEDECFORB,  State.TYPEDECFORB,  State.TYPEDECFORB,  State.INVALID,      State.IDFORB,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.CLOSEBRACE,   State.INVALID},
      /*CLOSEBRACE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONFINAL,   State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    
    //60
    
    /*REGQUALIFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.TYPEDECFORB,  State.SHORTFORB,    State.TYPEDECFORB,  State.LONGFIRSTFORB,State.TYPEDECFORB,  State.TYPEDECFORB,  State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*LONGFIRSTFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.LONGSECONDFORB,State.INVALID,     State.TYPEDECFORB,  State.INVALID,      State.INVALID,      State.IDFORB,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
  /*LONGSECONDFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEDECFORB,  State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDFORB,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*SHORTFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEDECFORB,  State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDFORB,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
     /*TYPEDECFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDFORB,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
          /*IDFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASSIGNOPFORB,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.ASSIGNOPFORB,     State.ASSIGNFORB,   State.INCDECFORB,   State.INVALID,      State.INVALID,      State.INVALID},
      /*ASSIGNFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMFORB,      State.IDFORBTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*IDFORBTWO*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONFORB,    State.OPFORB,           State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.OPFORB,           State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
         /*NUMFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONFORB,    State.OPFORB,           State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.OPFORB,           State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
          /*OPFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMFORB,      State.IDFORBTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*SEMICOLONFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.REGQUALIFORB, State.REGQUALIFORB,     State.TYPEDECFORB,  State.SHORTFORB,    State.TYPEDECFORB,  State.LONGFIRSTFORB,State.TYPEDECFORB,  State.TYPEDECFORB,  State.TYPEDECFORB,  State.INVALID,      State.IDFORB,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.CLOSEBRACE,   State.INVALID},
    /*ASSIGNOPFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.ASSIGNFORB,   State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
  /*SEMICOLONFINAL*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*INCDECFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONFORB,    State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},  
    };
    
    
    
    //METHODS
    
    public Checker(List<Token> tokens) {
        this.tokens = tokens;
    }
    
    
    public boolean check(){
        State currState = State.START;
        if(tokens.get(0).category == Category.FOR) {
            currState = State.STARFOR;
        } 
        setFuncText();
        for(Token token: tokens) {
            int first = currState.getValue();
            int second = token.getCategory().getValue();
            
            System.out.println("past state " + currState.getLabel());
            
            currState = table[first][second];
            
            System.out.println("token read " + token.getCategory().getLabel() + " " + token.getContent());
            System.out.println("current state " + currState.getLabel());
            System.out.println("");
            if (currState == State.INVALID) {
                return false;
            }
        }
        if(finalStates.contains(currState)) {
            return true;
        } else {
            return false;
        }
    }
    
    //for checking purposes
    public void printFinalStates() {
        for(State state: finalStates) {
            System.out.println(state.getValue());
        }
    }
    
    public void setFuncText() {
        int size = tokens.size();
        for(int i=0; i<size; i++) {
            if(tokens.get(i).isOpenParens()) {
                if(i!=0) {
                    Token toSet = tokens.get(i-1);
                    if(toSet.getCategory() == Category.VARTEXT) {
                        tokens.get(i-1).setCategory(Category.FUNCTEXT);
                    }
                }
            }
        }
    }
    
}
