
package up.cmsc141.julia.mp4final;

import java.util.ArrayList;
import java.util.List;


public class Checker {
    
    List<Token> tokens = new ArrayList<Token>();
    ArrayList<State> finalStates = new ArrayList<State>() {{
        add(State.SEMICOLONSTATE);
        add(State.SEMICOLONINC);
        add(State.CLOSEBRACE);
        add(State.SEMICOLONFINAL);
    }};
    
    private State[][] table = {
        //                                              CATEGORIES
        //  *STATE*     OPENPARENS                  CLOSEPARENS                 OPENBRACKET                 CLOSEBRACKET            COMMA               SEMICOLON               ASTERISK                SIGNED              UNSIGNED                CHAR                SHORT               INT                 LONG                FLOAT               DOUBLE              VOID                NUMTEXT             VARTEXT             FUNCTEXT                INVALIDCATEG                ANDOR               COMPARARTOR             OPERATION               EQUALS              INCDEC              FOR                 CLOSEBRACE              OPENBRACE                          
        /*  START */    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.REGQUALI,     State.REGQUALI,         State.TYPEDEC,      State.SHORTTYPE,    State.TYPEDEC,      State.LONGFIRST,    State.TYPEDEC,      State.TYPEDEC,      State.TYPEDEC,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*  TYPEDEC */    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASTERISKSTATE,    State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTDEC,   State.FUNCTEXTDEC,      State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*  VARTEXTDEC */    {   State.INVALID,          State.INVALID,              State.OPENBRACKETSTATE,     State.INVALID,          State.COMMASTATE,   State.SEMICOLONSTATE,   State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*  COMMASTATE */    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASTERISKSTATE,    State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTDEC,   State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*ASTERISKSTATE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASTERISKSTATE,    State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTDEC,   State.FUNCTEXTDEC,      State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
        /*REGQUALI*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.TYPEDEC,      State.SHORTTYPE,    State.TYPEDEC,      State.LONGFIRST,    State.TYPEDEC,      State.TYPEDEC,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*LONGFIRST*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASTERISKSTATE,    State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEDEC,      State.LONGSECOND,   State.INVALID,      State.TYPEDEC,      State.INVALID,      State.INVALID,      State.VARTEXTDEC,   State.FUNCTEXTDEC,      State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*LONGSECOND*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASTERISKSTATE,    State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEDEC,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTDEC,   State.FUNCTEXTDEC,      State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*SHORTTYPE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASTERISKSTATE,    State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEDEC,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTDEC,   State.FUNCTEXTDEC,      State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
        /*VOIDTYPE*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
  /*SEMICOLONSTATE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
/*OPENBRACKETSTATE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.CLOSEBRACKETSTATE,State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMTEXTSTATE, State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    /*NUMTEXTSTATE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.CLOSEBRACKETSTATE,State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
/*CLOSEBRACKETSTATE*/   {   State.INVALID,          State.INVALID,              State.OPENBRACKETSTATE,     State.INVALID,          State.INVALID,      State.SEMICOLONSTATE,   State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
     /*FUNCTEXTDEC*/    {   State.OPENPARENSSTATE,  State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
 /*OPENPARENSSTATE*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.REGQUALIFUNC, State.REGQUALIFUNC,     State.TYPEFUNC,     State.SHORTTYPEFUNC,State.TYPEFUNC,     State.LONGFIRSTFUNC,State.TYPEFUNC,     State.TYPEFUNC,     State.VOIDTYPE,     State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
        /*TYPEFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.OPENBRACKETFUNC,      State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.ASTERISKFUNC,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTFUNC,  State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},   
     /*VARTEXTFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.OPENBRACKETFUNC,      State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*COMMAFUNC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.TYPEFUNC,     State.SHORTTYPEFUNC,State.TYPEFUNC,     State.LONGFIRSTFUNC,State.TYPEFUNC,     State.TYPEFUNC,     State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
 /*OPENBRACKETFUNC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.CLOSEBRACKETFUNC, State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMTEXTFUNC,  State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
     /*NUMTEXTFUNC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.CLOSEBRACKETFUNC, State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
/*CLOSEBRACKETFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.OPENBRACKETFUNC,      State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    /*ASTERISKFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.INVALID,              State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.ASTERISKFUNC,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTFUNC,  State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
/*CLOSEPARENSSTATE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONSTATE,   State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    /*REGQUALIFUNC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.TYPEFUNC,     State.SHORTTYPEFUNC,State.TYPEFUNC,     State.LONGFIRSTFUNC,State.TYPEFUNC,     State.TYPEFUNC,     State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*LONGFIRSTFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.OPENBRACKETFUNC,      State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.ASTERISKFUNC,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.LONGSECONDFUNC,State.INVALID,     State.TYPEFUNC,     State.INVALID,      State.INVALID,      State.VARTEXTFUNC,  State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
  /*LONGSECONDFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.OPENBRACKETFUNC,      State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.ASTERISKFUNC,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEFUNC,     State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTFUNC,  State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*SHORTTYPEFUNC*/    {   State.INVALID,          State.CLOSEPARENSSTATE,     State.OPENBRACKETFUNC,      State.INVALID,          State.COMMAFUNC,    State.INVALID,          State.ASTERISKFUNC,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEFUNC,     State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.VARTEXTFUNC,  State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    /*INVALIDSTATE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},

        //  *STATE*     OPENPARENS                  CLOSEPARENS                 OPENBRACKET                 CLOSEBRACKET            COMMA               SEMICOLON               ASTERISK                SIGNED              UNSIGNED                CHAR                SHORT               INT                 LONG                FLOAT               DOUBLE              VOID                NUMTEXT             VARTEXT             FUNCTEXT                INVALIDCATEG                ANDOR               COMPARARTOR             OPERATION               EQUALS              INCDEC              FOR                 CLOSEBRACE          OPENBRACE                       
        /*STARTFOR*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.FORSTATE,     State.INVALID,      State.INVALID},
        /*FORSTATE*/    {   State.OPENPARENSFOR,    State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*OPENPARENSFOR*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONINIT,    State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINIT,      State.IDINIT,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
          /*IDINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.COMMAINIT,    State.SEMICOLONINIT,    State.OPASSIGNINIT,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.ANDORINIT,    State.COMPINIT,         State.OPASSIGNINIT,     State.ASSIGNINIT,  State.INCDECINIT,   State.INVALID,      State.INVALID,      State.INVALID},
   /*SEMICOLONINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONCOND,    State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMCOND,      State.IDCOND,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*INCDECINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.COMMAINIT,    State.SEMICOLONINIT,    State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*COMMAINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINIT,      State.IDINIT,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*ASSIGNINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINITTWO,   State.IDINITTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*NUMINITTWO*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.COMMAINIT,    State.SEMICOLONINIT,    State.OPINIT,           State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.ANDORINIT,    State.INVALID,          State.OPINIT,           State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*IDINITTWO*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.COMMAINIT,    State.SEMICOLONINIT,    State.OPINIT,           State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.ANDORINIT,    State.INVALID,          State.OPINIT,           State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
          /*OPINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINITTWO,   State.IDINITTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    /*OPASSIGNINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.ASSIGNINIT,   State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},  
        /*COMPINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINITTWO,   State.IDINITTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
         /*NUMINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.COMMAINIT,    State.SEMICOLONINIT,    State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.COMPINIT,         State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},

        //  *STATE*     OPENPARENS                  CLOSEPARENS                 OPENBRACKET                 CLOSEBRACKET            COMMA               SEMICOLON               ASTERISK                SIGNED              UNSIGNED                CHAR                SHORT               INT                 LONG                FLOAT               DOUBLE              VOID                NUMTEXT             VARTEXT             FUNCTEXT                INVALIDCATEG                ANDOR               COMPARARTOR             OPERATION               EQUALS              INCDEC              FOR                 CLOSEBRACE          OPENBRACE                                
          /*OPCOND*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMCONDTWO,   State.IDCONDTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},     
          /*IDCOND*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONCOND,    State.OPASSIGNCOND,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.ANDOR,        State.COMPARATOR,       State.OPASSIGNCOND,     State.INVALID,      State.INCDECCOND,   State.INVALID,      State.INVALID,      State.INVALID},
      /*COMPARATOR*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMCONDTWO,   State.IDCONDTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*IDCONDTWO*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONCOND,    State.OPCOND,           State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.ANDOR,        State.INVALID,          State.OPCOND,           State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*NUMCONDTWO*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONCOND,    State.OPCOND,           State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.ANDOR,        State.INVALID,          State.OPCOND,           State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
           /*ANDOR*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMCOND,      State.IDCOND,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*SEMICOLONCOND*/    {   State.INVALID,          State.CLOSEPARENSFOR,       State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINC,       State.IDINC,        State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*INCDECCOND*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.ANDOR,        State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
         /*NUMCOND*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONCOND,    State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.ANDOR,        State.COMPARATOR,       State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    /*OPASSIGNCOND*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.ASSIGNCOND,   State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*ASSIGNCOND*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMCONDTWO,   State.IDCONDTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      
        //  *STATE*     OPENPARENS                  CLOSEPARENS                 OPENBRACKET                 CLOSEBRACKET            COMMA               SEMICOLON               ASTERISK                SIGNED              UNSIGNED                CHAR                SHORT               INT                 LONG                FLOAT               DOUBLE              VOID                NUMTEXT             VARTEXT             FUNCTEXT                INVALIDCATEG                ANDOR               COMPARARTOR             OPERATION               EQUALS              INCDEC              FOR                 CLOSEBRACE          OPENBRACE                                 
           /*IDINC*/    {   State.INVALID,          State.CLOSEPARENSFOR,       State.INVALID,              State.INVALID,          State.COMMAINC,     State.INVALID,          State.OPASSIGNINC,      State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.ANDORINC,     State.COMPINC,          State.OPASSIGNINC,      State.ASSIGNINC,    State.INCDEC,       State.INVALID,      State.INVALID,      State.INVALID},          
          /*INCDEC*/    {   State.INVALID,          State.CLOSEPARENSFOR,       State.INVALID,              State.INVALID,          State.COMMAINC,     State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*ASSIGNINC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINCTWO,    State.IDINCTWO,     State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
        /*COMMAINC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINC,       State.IDINC,        State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
  /*CLOSEPARENSFOR*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONINC,     State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.OPENBRACE},
        /*IDINCTWO*/    {   State.INVALID,          State.CLOSEPARENSFOR,       State.INVALID,              State.INVALID,          State.COMMAINC,     State.INVALID,          State.OPINC,            State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.ANDORINC,     State.INVALID,          State.OPINC,            State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*NUMINCTWO*/    {   State.INVALID,          State.CLOSEPARENSFOR,       State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.OPINC,            State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.ANDORINC,     State.INVALID,          State.OPINC,            State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
           /*OPINC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINCTWO,    State.IDINCTWO,     State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
    /*SEMICOLONINC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
     /*OPASSIGNINC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.ASSIGNINC,    State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
         /*COMPINC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINCTWO,    State.IDINCTWO,     State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
          /*NUMINC*/    {   State.INVALID,          State.CLOSEPARENSFOR,       State.INVALID,              State.INVALID,          State.COMMAINC,     State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.COMPINC,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
          
        //  *STATE*     OPENPARENS                  CLOSEPARENS                 OPENBRACKET                 CLOSEBRACKET            COMMA               SEMICOLON               ASTERISK                SIGNED              UNSIGNED                CHAR                SHORT               INT                 LONG                FLOAT               DOUBLE              VOID                NUMTEXT             VARTEXT             FUNCTEXT                INVALIDCATEG                ANDOR               COMPARARTOR             OPERATION               EQUALS              INCDEC              FOR                 CLOSEBRACE          OPENBRACE                           
       /*OPENBRACE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONFORB,    State.INVALID,          State.REGQUALIFORB, State.REGQUALIFORB,     State.TYPEDECFORB,  State.SHORTFORB,    State.TYPEDECFORB,  State.LONGFIRSTFORB,State.TYPEDECFORB,  State.TYPEDECFORB,  State.TYPEDECFORB,  State.NUMFORBTWO,   State.IDFORB,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.CLOSEBRACE,   State.INVALID},
      /*CLOSEBRACE*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONFINAL,   State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID}, 
    /*REGQUALIFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.TYPEDECFORB,  State.SHORTFORB,    State.TYPEDECFORB,  State.LONGFIRSTFORB,State.TYPEDECFORB,  State.TYPEDECFORB,  State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*LONGFIRSTFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.LONGSECONDFORB,State.INVALID,     State.TYPEDECFORB,  State.INVALID,      State.INVALID,      State.IDFORB,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
  /*LONGSECONDFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEDECFORB,  State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDFORB,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*SHORTFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.TYPEDECFORB,  State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDFORB,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
     /*TYPEDECFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.IDFORB,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
          /*IDFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.ASSIGNOPFORB,     State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.ANDORFORB,    State.COMPFORB,         State.ASSIGNOPFORB,     State.ASSIGNFORB,   State.INCDECFORB,   State.INVALID,      State.INVALID,      State.INVALID},
      /*ASSIGNFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMFORB,      State.IDFORBTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*IDFORBTWO*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONFORB,    State.OPFORB,           State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.OPFORB,           State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
         /*NUMFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONFORB,    State.OPFORB,           State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.OPFORB,           State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
          /*OPFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMFORB,      State.IDFORBTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
   /*SEMICOLONFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONFORB,    State.INVALID,          State.REGQUALIFORB, State.REGQUALIFORB,     State.TYPEDECFORB,  State.SHORTFORB,    State.TYPEDECFORB,  State.LONGFIRSTFORB,State.TYPEDECFORB,  State.TYPEDECFORB,  State.TYPEDECFORB,  State.NUMFORB,      State.IDFORB,       State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.CLOSEBRACE,   State.INVALID},
    /*ASSIGNOPFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.ASSIGNFORB,   State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
  /*SEMICOLONFINAL*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*INCDECFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONFORB,    State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},  
        /*COMPFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMFORB,      State.IDFORBTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
      /*NUMFORBTWO*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.SEMICOLONFORB,    State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*ANDORINIT*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINITTWO,   State.IDINITTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
        /*ANDORINC*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMINCTWO,    State.IDINCTWO,     State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID},
       /*ANDORFORB*/    {   State.INVALID,          State.INVALID,              State.INVALID,              State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.NUMFORB,      State.IDFORBTWO,    State.INVALID,          State.INVALID,              State.INVALID,      State.INVALID,          State.INVALID,          State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID,      State.INVALID}
    };
    
    public Checker(List<Token> tokens) {
        this.tokens = tokens;
    }
        
    public boolean check(){
        State currState = State.START;
        if(tokens.get(0).category == Category.FOR) {
            currState = State.STARFOR;
        } 
        setFuncText();
        for(Token token: tokens) {
            int first = currState.getValue(); //index of current state in the table
            int second = token.getCategory().getValue(); //index of category of token being read in the table           
            currState = table[first][second];
        
            if (currState == State.INVALID) {
                return false;
            }
        }
        //if the last state is a final state, return true
        if(finalStates.contains(currState)) {
            return true;
        } else {
            return false;
        }
    }
    
    //for checking purposes
    public void printFinalStates() {
        for(State state: finalStates) {
            System.out.println(state.getValue());
        }
    }
    
    public void setFuncText() {
        int size = tokens.size();
        for(int i=0; i<size; i++) {
            if(tokens.get(i).isOpenParens()) {
                if(i!=0) {
                    Token toSet = tokens.get(i-1);
                    if(toSet.getCategory() == Category.VARTEXT) {
                        tokens.get(i-1).setCategory(Category.FUNCTEXT);
                    }
                }
            }
        }
    }
    
}
