/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package up.cmsc141.julia.mp4.test3;

/**
 *
 * @author juliam
 */
public enum State {
    START(0, "START"),
    TYPEDEC(1, "TYPEDEC"),
    VARTEXTDEC(2, "VARTEXTDEC"),
    COMMASTATE(3, "COMMASTATE"),
    ASTERISKSTATE(4, "ASTERISKSTATE"),
    REGQUALI(5, "REGQUALI"),
    LONGFIRST(6, "LONGFIRST"),
    LONGSECOND(7, "LONGSECOND"),
    SHORTTYPE(8, "SHORTTYPE"),
    VOIDTYPE(9, "VOIDTYPE"),
    SEMICOLONSTATE(10, "SEMICOLONSTATE"),
    OPENBRACKETSTATE(11, "OPENBRACKETSTATE"),
    NUMTEXTSTATE(12, "NUMTEXTSTAE"),
    CLOSEBRACKETSTATE(13, "CLOSEBRACKETSTATE"),
    FUNCTEXTDEC(14, "FUNCTEXTDEC"),
    OPENPARENSSTATE(15, "OPENPARENSSTATE"),
    TYPEFUNC(16, "TYPEFUNC"),
    VARTEXTFUNC(17, "VARTEXTFUNC"),
    COMMAFUNC(18, "COMMAFUNC"),
    OPENBRACKETFUNC(19, "OPENBRACKETFUNC"),
    NUMTEXTFUNC(20, "NUMTEXTFUNC"),
    CLOSEBRACKETFUNC(21, "CLOSEBRACKETFUNC"),
    ASTERISKFUNC(22, "ASTERISKFUNC"),
    CLOSEPARENSSTATE(23, "CLOSEPARENSSTATE"),
    REGQUALIFUNC(24, "REGQUALIFUNC"),
    LONGFIRSTFUNC(25, "LONGFIRSTFUNC"),
    LONGSECONDFUNC(26, "LONGSECONDFUNC"),
    SHORTTYPEFUNC(27, "SHORTTYPEFUNC"),
    INVALID(28, "INVALID"),
    STARFOR(29, "STARTFOR"),
    FORSTATE(30, "FORSTATE"),
    OPENPARENSFOR(31, "OPENPARENSFOR"),
    IDINIT(32, "IDINIT"),
    SEMICOLONINIT(33, "SEMICOLONINIT"),
    INCDECINIT(34, "INCDECINIT"),
    COMMAINIT(35, "COMMAINIT"),
    ASSIGNINIT(36, "ASSIGNINIT"),
    NUMINITTWO(37, "NUMINITTWO"),
    IDINITTWO(38, "IDINITTWO"),
    OPINIT(39, "OPINIT"),
    OPASSIGNINIT(40, "OPASSIGNINIT"),
    COMPINIT(41,"COMPINIT"),
    NUMINIT(42, "NUMINIT"),
    OPCOND(43, "OPCOND"),
    IDCOND(44, "IDCOND"),
    COMPARATOR(45, "COMPARATOR"),
    IDCONDTWO(46, "IDCONDTWO"),
    NUMCONDTWO(47, "NUMCONDTWO"),
    ANDOR(48, "ANDOR"),
    SEMICOLONCOND(49, "SEMICOLONCOND"),
    INCDECCOND(50, "INCDECCOND"),
    NUMCOND(51, "NUMCOND"),
    OPASSIGNCOND(52, "OPASSIGNCOND"),
    ASSIGNCOND(53, "ASSIGNCOND"),
    IDINC(54, "IDINC"),
    INCDEC(55, "INCDEC"),
    ASSIGNINC(56, "ASSIGNINC"),
    COMMAINC(57, "COMMAINC"),
    CLOSEPARENSFOR(58, "CLOSEPARENSFOR"),
    IDINCTWO(59, "IDINCTWO"),
    NUMINCTWO(60, "NUMINCTW0"),
    OPINC(61, "OPINC"),
    SEMICOLONINC(62, "SEMICOLONINC"),
    OPASSIGNINC(63, "OPASSIGNINC"),
    COMPINC(64, "COMPINC"),
    NUMINC(65, "NUMINC"),
    OPENBRACE(66, "OPENBRACE"),
    CLOSEBRACE(67, "CLOSEBRACE"),
    REGQUALIFORB(68, "REGQUALIFORB"),
    LONGFIRSTFORB(69, "LONGFIRSTFORB"),
    LONGSECONDFORB(70, "LONGSECONDFORB"),
    SHORTFORB(71, "SHORTFORB"),
    TYPEDECFORB(72, "TYPEDECFORB"),
    IDFORB(73, "IDFORB"),
    ASSIGNFORB(74, "ASSIGNFORB"),
    IDFORBTWO(75, "IDFORBTWO"),
    NUMFORB(76, "NUMFORB"),
    OPFORB(77, "OPFORB"),
    SEMICOLONFORB(78, "SEMICOLONFORB"),
    ASSIGNOPFORB(79, "ASSIGNOPFORB"),
    SEMICOLONFINAL(80, "SEMICOLONFINAL"),
    INCDECFORB(81, "INCDECFORB");
   
   private final int value;
   private final String label;
   State(int value, String label) {
       this.value = value;
       this.label = label;
   }
   
   public int getValue() {
       return value;
   }
   
   public String getLabel() {
       return label;
   }
}

