/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package up.cmsc141.julia.mp4.test2;

/**
 *
 * @author juliam
 */
public enum State {
    START(0, "START"),
    TYPEDEC(1, "TYPEDEC"),
    VARTEXTDEC(2, "VARTEXTDEC"),
    COMMASTATE(3, "COMMASTATE"),
    ASTERISKSTATE(4, "ASTERISKSTATE"),
    REGQUALI(5, "REGQUALI"),
    LONGFIRST(6, "LONGFIRST"),
    LONGSECOND(7, "LONGSECOND"),
    SHORTTYPE(8, "SHORTTYPE"),
    VOIDTYPE(9, "VOIDTYPE"),
    SEMICOLONSTATE(10, "SEMICOLONSTATE"),
    OPENBRACKETSTATE(11, "OPENBRACKETSTATE"),
    NUMTEXTSTATE(12, "NUMTEXTSTAE"),
    CLOSEBRACKETSTATE(13, "CLOSEBRACKETSTATE"),
    FUNCTEXTDEC(14, "FUNCTEXTDEC"),
    OPENPARENSSTATE(15, "OPENPARENSSTATE"),
    TYPEFUNC(16, "TYPEFUNC"),
    VARTEXTFUNC(17, "VARTEXTFUNC"),
    COMMAFUNC(18, "COMMAFUNC"),
    OPENBRACKETFUNC(19, "OPENBRACKETFUNC"),
    NUMTEXTFUNC(20, "NUMTEXTFUNC"),
    CLOSEBRACKETFUNC(21, "CLOSEBRACKETFUNC"),
    ASTERISKFUNC(22, "ASTERISKFUNC"),
    CLOSEPARENSSTATE(23, "CLOSEPARENSSTATE"),
    REGQUALIFUNC(24, "REGQUALIFUNC"),
    LONGFIRSTFUNC(25, "LONGFIRSTFUNC"),
    LONGSECONDFUNC(26, "LONGSECONDFUNC"),
    SHORTTYPEFUNC(27, "SHORTTYPEFUNC"),
    INVALID(28, "INVALID"),
    STARFOR(29, "STARTFOR"),
    FORSTATE(30, "FORSTATE"),
    OPENPARENSFOR(31, "OPENPARENSFOR"),
    REGQUALIINIT(32, "REGQUALIINIT"),
    LONGFIRSTINIT(33, "LONGFIRSTINIT"),
    LONGSECONDFOR(34, "LONGSECONDFOR"),
    SHORTINIT(35, "SHORTINIT"),
    IDINIT(36, "IDINIT"),
    SEMICOLONINIT(37, "SEMICOLONINIT"),
    TYPEDECINIT(38, "TYPEDECINIT"),
    COMMAINIT(39, "COMMAINIT"),
    ASSIGNINIT(40, "ASSIGNINIT"),
    NUMINIT(41, "NUMINIT"),
    IDINITTWO(42, "IDINITTWO"),
    OPINIT(43, "OPINIT"),
    IDCOND(44, "IDCOND"),
    COMPARATOR(45, "COMPARATOR"),
    IDCONDTWO(46, "IDCONDTWO"),
    NUMCOND(47, "NUMCOND"),
    ANDOR(48, "ANDOR"),
    SEMICOLONCOND(49, "SEMICOLONCOND"),
    IDINC(50, "IDINC"),
    INCDEC(51, "INCDEC"),
    ASSIGNINC(52, "ASSIGNINC"),
    COMMAINC(53, "COMMAINC"),
    CLOSEPARENSFOR(54, "CLOSEPARENSFOR"),
    IDINCTWO(55, "IDINCTWO"),
    NUMINC(56, "NUMINC"),
    OPINC(57, "OPINC"),
    SEMICOLONINC(58, "SEMICOLONINC"),
    OPENBRACE(59, "OPENBRACE"),
    CLOSEBRACE(60, "CLOSEBRACE"),
    REGQUALIFORB(61, "REGQUALIFORB"),
    LONGFIRSTFORB(62, "LONGFIRSTFORB"),
    LONGSECONDFORB(63, "LONGSECONDFORB"),
    SHORTFORB(64, "SHORTFORB"),
    TYPEDECFORB(65, "TYPEDECFORB"),
    IDFORB(66, "IDFORB"),
    ASSIGNFORB(67, "ASSIGNFORB"),
    IDFORBTWO(68, "IDFORBTWO"),
    NUMFORB(69, "NUMFORB"),
    OPFORB(70, "OPFORB"),
    SEMICOLONFORB(71, "SEMICOLONFORB"),
    ASSIGNOPFORB(72, "ASSIGNOPFORB"),
    SEMICOLONFINAL(73, "SEMICOLONFINAL"),
    INCDECFORB(74, "INCDECFORB");
   
   private final int value;
   private final String label;
   State(int value, String label) {
       this.value = value;
       this.label = label;
   }
   
   public int getValue() {
       return value;
   }
   
   public String getLabel() {
       return label;
   }
}

